import type { ModelDef } from "@koryphaios/shared";

export const AnthropicModels: ModelDef[] = [
  // Current Models (2025-2026)
  {
    id: "claude-opus-4-6",
    name: "Claude 4.6 Opus",
    provider: "anthropic",
    apiModelId: "claude-opus-4-6",
    contextWindow: 200_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 5.0,
    costPerMOutputTokens: 25.0,
    costPerMInputCached: 6.25,
    costPerMOutputCached: 0.50,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude 4.5 Sonnet",
    provider: "anthropic",
    apiModelId: "claude-sonnet-4-5-20250929",
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 3.75,
    costPerMOutputCached: 0.30,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude 4.5 Haiku",
    provider: "anthropic",
    apiModelId: "claude-haiku-4-5-20251001",
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.80,
    costPerMOutputTokens: 4.0,
    costPerMInputCached: 1.0,
    costPerMOutputCached: 0.08,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },

  // Legacy Models
  {
    id: "claude-4-sonnet",
    name: "Claude 4 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-sonnet-4-20250514",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 3.75,
    costPerMOutputCached: 0.30,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-4-opus",
    name: "Claude 4 Opus (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-opus-4-20250514",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 75.0,
    costPerMInputCached: 18.75,
    costPerMOutputCached: 1.50,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-7-sonnet-20250219",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 3.75,
    costPerMOutputCached: 0.30,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-5-sonnet-20241022",
    contextWindow: 200_000,
    maxOutputTokens: 5_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 3.75,
    costPerMOutputCached: 0.30,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-3.5-haiku",
    name: "Claude 3.5 Haiku (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-5-haiku-20241022",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.80,
    costPerMOutputTokens: 4.0,
    costPerMInputCached: 1.0,
    costPerMOutputCached: 0.08,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-haiku-20240307",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.25,
    costPerMOutputTokens: 1.25,
    costPerMInputCached: 0.30,
    costPerMOutputCached: 0.03,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-opus-20240229",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 75.0,
    costPerMInputCached: 18.75,
    costPerMOutputCached: 1.50,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
];
