import type { ModelDef } from "@koryphaios/shared";

export const AnthropicModels: ModelDef[] = [
  // Current Models (February 2026)
  {
    id: "claude-opus-4-6",
    name: "Claude 4.6 Opus",
    provider: "anthropic",
    apiModelId: "claude-opus-4-6-20260205",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 5.0,
    costPerMOutputTokens: 25.0,
    costPerMInputCached: 1.25,
    costPerMOutputCached: 0.10,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude 4.5 Sonnet",
    provider: "anthropic",
    apiModelId: "claude-sonnet-4-5-20260213",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0.75,
    costPerMOutputCached: 0.08,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude 4.5 Haiku",
    provider: "anthropic",
    apiModelId: "claude-haiku-4-5-20260213",
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.50,
    costPerMOutputTokens: 2.50,
    costPerMInputCached: 0.10,
    costPerMOutputCached: 0.02,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },

  // Legacy Models (Retired/Deprecated)
  {
    id: "claude-opus-4",
    name: "Claude 4 Opus (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-opus-4-20250514",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    tier: "flagship",
  },
  {
    id: "claude-sonnet-4",
    name: "Claude 4 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-sonnet-4-20250514",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    tier: "flagship",
  },
  {
    id: "claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-7-sonnet-20250219",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    tier: "flagship",
  },
  {
    id: "claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-5-sonnet-20241022",
    contextWindow: 200_000,
    maxOutputTokens: 5_000,
    tier: "flagship",
  },
  {
    id: "claude-3.5-haiku",
    name: "Claude 3.5 Haiku (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-5-haiku-20241022",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    tier: "fast",
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-haiku-20240307",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    tier: "fast",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-opus-20240229",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    tier: "flagship",
  },
];
