import type { ModelDef } from "@koryphaios/shared";

export const CopilotModels: ModelDef[] = [
  {
    id: "copilot.gpt-3.5-turbo",
    name: "GitHub Copilot GPT-3.5-turbo",
    provider: "copilot",
    apiModelId: "gpt-3.5-turbo",
    contextWindow: 16_384,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "copilot.gpt-4o",
    name: "GitHub Copilot GPT-4o",
    provider: "copilot",
    apiModelId: "gpt-4o",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.gpt-4o-mini",
    name: "GitHub Copilot GPT-4o Mini",
    provider: "copilot",
    apiModelId: "gpt-4o-mini",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "copilot.gpt-4.1",
    name: "GitHub Copilot GPT-4.1",
    provider: "copilot",
    apiModelId: "gpt-4.1",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.claude-3.5-sonnet",
    name: "GitHub Copilot Claude 3.5 Sonnet",
    provider: "copilot",
    apiModelId: "claude-3.5-sonnet",
    contextWindow: 90_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.claude-3.7-sonnet",
    name: "GitHub Copilot Claude 3.7 Sonnet",
    provider: "copilot",
    apiModelId: "claude-3.7-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.claude-sonnet-4",
    name: "GitHub Copilot Claude Sonnet 4",
    provider: "copilot",
    apiModelId: "claude-sonnet-4",
    contextWindow: 128_000,
    maxOutputTokens: 16_000,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.o1",
    name: "GitHub Copilot o1",
    provider: "copilot",
    apiModelId: "o1",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "copilot.o3-mini",
    name: "GitHub Copilot o3-mini",
    provider: "copilot",
    apiModelId: "o3-mini",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "copilot.o4-mini",
    name: "GitHub Copilot o4-mini",
    provider: "copilot",
    apiModelId: "o4-mini",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "copilot.gemini-2.0-flash",
    name: "GitHub Copilot Gemini 2.0 Flash",
    provider: "copilot",
    apiModelId: "gemini-2.0-flash-001",
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "copilot.gemini-2.5-pro",
    name: "GitHub Copilot Gemini 2.5 Pro",
    provider: "copilot",
    apiModelId: "gemini-2.5-pro",
    contextWindow: 128_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.gpt-4",
    name: "GitHub Copilot GPT-4",
    provider: "copilot",
    apiModelId: "gpt-4",
    contextWindow: 32_768,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "copilot.claude-3.7-sonnet-thought",
    name: "GitHub Copilot Claude 3.7 Sonnet Thinking",
    provider: "copilot",
    apiModelId: "claude-3.7-sonnet-thought",
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.0,
    costPerMOutputTokens: 0.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
];
