import type { ModelDef } from "@koryphaios/shared";

/**
 * Official Gemini CLI Models (Exact IDs)
 * These IDs map to what the 'gcloud' / 'gemini' CLI expects.
 */
export const GeminiModels: ModelDef[] = [
  // Current Models (February 2026)
  {
    id: "gemini-3-deep-think",
    name: "Gemini 3 Deep Think",
    provider: "google",
    apiModelId: "gemini-3-deep-think-20260212",
    contextWindow: 2_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 2.0,
    costPerMOutputTokens: 20.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    provider: "google",
    apiModelId: "gemini-3-pro-001",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 1.25,
    costPerMOutputTokens: 10.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    provider: "google",
    apiModelId: "gemini-3-flash-001",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.10,
    costPerMOutputTokens: 0.40,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    apiModelId: "gemini-2.5-pro",
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    costPerMInputTokens: 3.50,
    costPerMOutputTokens: 10.50,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    apiModelId: "gemini-2.5-flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.075,
    costPerMOutputTokens: 0.30,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    provider: "google",
    apiModelId: "gemini-2.5-flash-lite",
    contextWindow: 1_000_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.01,
    costPerMOutputTokens: 0.01,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "cheap",
  },

  // Legacy Models
  {
    id: "gemini-2.0-pro-exp",
    name: "Gemini 2.0 Pro Experimental (Legacy)",
    provider: "google",
    apiModelId: "gemini-2.0-pro-exp-02-05",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    tier: "flagship",
  },
  {
    id: "gemini-2.0-flash-exp",
    name: "Gemini 2.0 Flash Experimental (Legacy)",
    provider: "google",
    apiModelId: "gemini-2.0-flash-exp",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    tier: "fast",
  },
];

/**
 * Google Antigravity Exclusive Models
 */
export const AntigravityModels: ModelDef[] = [
  {
    id: "antigravity.gemini-3-pro",
    name: "Antigravity Gemini 3 Pro",
    provider: "antigravity",
    apiModelId: "gemini-3-pro",
    contextWindow: 2_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "antigravity.gemini-3-flash",
    name: "Antigravity Gemini 3 Flash",
    provider: "antigravity",
    apiModelId: "gemini-3-flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "antigravity.gemini-3-deep-think",
    name: "Antigravity Gemini 3 Deep Think",
    provider: "antigravity",
    apiModelId: "gemini-3-deep-think",
    contextWindow: 2_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "antigravity.nano-banana-pro",
    name: "Nano Banana Pro (Gemini 3 Pro Image)",
    provider: "antigravity",
    apiModelId: "nano-banana-pro",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "cheap",
  },
];
