import type { ModelDef } from "@koryphaios/shared";

/**
 * Official Gemini CLI Models (Exact IDs)
 * These IDs map to what the 'gemini' CLI expects in its --model flag.
 */
export const GeminiModels: ModelDef[] = [
  // Auto-Select Models (CLI dynamic mapping)
  {
    id: "auto-gemini-3",
    name: "Gemini 3 (Auto)",
    provider: "google",
    apiModelId: "gemini-3",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "auto-gemini-2.5",
    name: "Gemini 2.5 (Auto)",
    provider: "google",
    apiModelId: "gemini-2.5",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.10,
    costPerMOutputTokens: 0.40,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },

  // Specific Model Versions
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    provider: "google",
    apiModelId: "gemini-3-pro-experimental", // Exact CLI ID
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 1.50,
    costPerMOutputTokens: 15.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    provider: "google",
    apiModelId: "gemini-3-flash-experimental", // Exact CLI ID
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "gemini-2.0-pro-exp",
    name: "Gemini 2.0 Pro Experimental",
    provider: "google",
    apiModelId: "gemini-2.0-pro-exp-02-05", // Exact API/CLI ID
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "gemini-2.0-flash-exp",
    name: "Gemini 2.0 Flash Experimental",
    provider: "google",
    apiModelId: "gemini-2.0-flash-exp",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    apiModelId: "gemini-2.5-flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 0.30,
    costPerMOutputTokens: 2.50,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    apiModelId: "gemini-2.5-pro",
    contextWindow: 1_000_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.25,
    costPerMOutputTokens: 10.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
];

/**
 * Google Antigravity Exclusive Models
 * These models are typically only available via the Antigravity Unified Gateway.
 */
export const AntigravityModels: ModelDef[] = [
  {
    id: "antigravity.gemini-3-pro",
    name: "Antigravity Gemini 3 Pro",
    provider: "antigravity",
    apiModelId: "gemini-3-pro",
    contextWindow: 2_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "antigravity.gemini-3-flash",
    name: "Antigravity Gemini 3 Flash",
    provider: "antigravity",
    apiModelId: "gemini-3-flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "antigravity.gemini-3-deep-think",
    name: "Antigravity Gemini 3 Deep Think",
    provider: "antigravity",
    apiModelId: "gemini-3-deep-think",
    contextWindow: 2_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "antigravity.nano-banana-pro",
    name: "Nano Banana Pro (Gemini 2.5 Flash Image)",
    provider: "antigravity",
    apiModelId: "nano-banana-pro",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "cheap",
  },
  {
    id: "antigravity.gemini-2.5-pro-ui",
    name: "Gemini 2.5 Pro UI Checkpoint",
    provider: "antigravity",
    apiModelId: "gemini-2.5-pro-ui-checkpoint",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
];
