import type { ModelDef } from "@koryphaios/shared";

export const OpenRouterModels: ModelDef[] = [
  {
    id: "openrouter.gpt-4.1",
    name: "OpenRouter – GPT 4.1",
    provider: "openrouter",
    apiModelId: "openai/gpt-4.1",
    contextWindow: 1_047_576,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 2.0,
    costPerMOutputTokens: 8.0,
    costPerMInputCached: 0.50,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.gpt-4.1-mini",
    name: "OpenRouter – GPT 4.1 mini",
    provider: "openrouter",
    apiModelId: "openai/gpt-4.1-mini",
    contextWindow: 200_000,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 0.40,
    costPerMOutputTokens: 1.60,
    costPerMInputCached: 0.10,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "openrouter.gpt-4.1-nano",
    name: "OpenRouter – GPT 4.1 nano",
    provider: "openrouter",
    apiModelId: "openai/gpt-4.1-nano",
    contextWindow: 1_047_576,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 0.10,
    costPerMOutputTokens: 0.40,
    costPerMInputCached: 0.025,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "cheap",
  },
  {
    id: "openrouter.gpt-4.5-preview",
    name: "OpenRouter – GPT 4.5 preview",
    provider: "openrouter",
    apiModelId: "openai/gpt-4.5-preview",
    contextWindow: 128_000,
    maxOutputTokens: 15_000,
    costPerMInputTokens: 75.0,
    costPerMOutputTokens: 150.0,
    costPerMInputCached: 37.50,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.gpt-4o",
    name: "OpenRouter – GPT 4o",
    provider: "openrouter",
    apiModelId: "openai/gpt-4o",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 2.50,
    costPerMOutputTokens: 10.0,
    costPerMInputCached: 1.25,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.gpt-4o-mini",
    name: "OpenRouter – GPT 4o mini",
    provider: "openrouter",
    apiModelId: "openai/gpt-4o-mini",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    costPerMInputCached: 0.075,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "openrouter.o1",
    name: "OpenRouter – O1",
    provider: "openrouter",
    apiModelId: "openai/o1",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 60.0,
    costPerMInputCached: 7.50,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "openrouter.o1-pro",
    name: "OpenRouter – o1 pro",
    provider: "openrouter",
    apiModelId: "openai/o1-pro",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 150.0,
    costPerMOutputTokens: 600.0,
    costPerMInputCached: 0.0,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "openrouter.o1-mini",
    name: "OpenRouter – o1 mini",
    provider: "openrouter",
    apiModelId: "openai/o1-mini",
    contextWindow: 128_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "openrouter.o3",
    name: "OpenRouter – o3",
    provider: "openrouter",
    apiModelId: "openai/o3",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 10.0,
    costPerMOutputTokens: 40.0,
    costPerMInputCached: 2.50,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "openrouter.o3-mini",
    name: "OpenRouter – o3 mini",
    provider: "openrouter",
    apiModelId: "openai/o3-mini-high",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "openrouter.o4-mini",
    name: "OpenRouter – o4 mini",
    provider: "openrouter",
    apiModelId: "openai/o4-mini-high",
    contextWindow: 128_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.275,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "openrouter.gemini-2.5-flash",
    name: "OpenRouter – Gemini 2.5 Flash",
    provider: "openrouter",
    apiModelId: "google/gemini-2.5-flash-preview:thinking",
    contextWindow: 1_000_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "openrouter.gemini-2.5",
    name: "OpenRouter – Gemini 2.5 Pro",
    provider: "openrouter",
    apiModelId: "google/gemini-2.5-pro-preview-03-25",
    contextWindow: 1_000_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.25,
    costPerMOutputTokens: 10.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.claude-3.5-sonnet",
    name: "OpenRouter – Claude 3.5 Sonnet",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3.5-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 5_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 3.75,
    costPerMOutputCached: 0.30,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.claude-3-haiku",
    name: "OpenRouter – Claude 3 Haiku",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3-haiku",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.25,
    costPerMOutputTokens: 1.25,
    costPerMInputCached: 0.30,
    costPerMOutputCached: 0.03,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "openrouter.claude-3.7-sonnet",
    name: "OpenRouter – Claude 3.7 Sonnet",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3.7-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 3.75,
    costPerMOutputCached: 0.30,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.claude-3.5-haiku",
    name: "OpenRouter – Claude 3.5 Haiku",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3.5-haiku",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.80,
    costPerMOutputTokens: 4.0,
    costPerMInputCached: 1.0,
    costPerMOutputCached: 0.08,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "openrouter.claude-3-opus",
    name: "OpenRouter – Claude 3 Opus",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3-opus",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 75.0,
    costPerMInputCached: 18.75,
    costPerMOutputCached: 1.50,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.deepseek-r1-free",
    name: "OpenRouter – DeepSeek R1 Free",
    provider: "openrouter",
    apiModelId: "deepseek/deepseek-r1-0528:free",
    contextWindow: 163_840,
    maxOutputTokens: 10_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "cheap",
  },
];
