import type { ModelDef } from "@koryphaios/shared";

export const XAIModels: ModelDef[] = [
  // Current Models (February 2026) - Verified from docs.x.ai/developers/models
  {
    id: "grok-4-1-fast-reasoning",
    name: "Grok 4.1 Fast Reasoning",
    provider: "xai",
    apiModelId: "grok-4-1-fast-reasoning",
    contextWindow: 2_000_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 0.20,
    costPerMOutputTokens: 0.50,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast",
    provider: "xai",
    apiModelId: "grok-4-1-fast-non-reasoning",
    contextWindow: 2_000_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 0.20,
    costPerMOutputTokens: 0.50,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "grok-code-fast-1",
    name: "Grok Code Fast 1",
    provider: "xai",
    apiModelId: "grok-code-fast-1",
    contextWindow: 256_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 0.20,
    costPerMOutputTokens: 1.50,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "grok-4-0709",
    name: "Grok 4 (Stable)",
    provider: "xai",
    apiModelId: "grok-4-0709",
    contextWindow: 256_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xai",
    apiModelId: "grok-3",
    contextWindow: 131_072,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-3-mini",
    name: "Grok 3 Mini",
    provider: "xai",
    apiModelId: "grok-3-mini",
    contextWindow: 131_072,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 0.30,
    costPerMOutputTokens: 0.50,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
];
