import type { ModelDef } from "@koryphaios/shared";

export const XAIModels: ModelDef[] = [
  // Current Models (July 2025+)
  {
    id: "grok-4-0709",
    name: "Grok 4",
    provider: "xai",
    apiModelId: "grok-4",
    contextWindow: 256_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-4",
    name: "Grok 4",
    provider: "xai",
    apiModelId: "grok-4",
    contextWindow: 256_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-4-1",
    name: "Grok 4.1",
    provider: "xai",
    apiModelId: "grok-4-1",
    contextWindow: 256_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-4-1-fast",
    name: "Grok 4.1 Fast",
    provider: "xai",
    apiModelId: "grok-4-1-fast",
    contextWindow: 2_000_000,
    maxOutputTokens: 30_000,
    costPerMInputTokens: 0.20,
    costPerMOutputTokens: 0.50,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },

  // Legacy Models
  {
    id: "grok-3-beta",
    name: "Grok 3 Beta (Legacy)",
    provider: "xai",
    apiModelId: "grok-3-beta",
    contextWindow: 131_072,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xai",
    apiModelId: "grok-3",
    contextWindow: 131_072,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "grok-3-mini-beta",
    name: "Grok 3 Mini Beta (Legacy)",
    provider: "xai",
    apiModelId: "grok-3-mini-beta",
    contextWindow: 131_072,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 0.30,
    costPerMOutputTokens: 0.50,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
];
